### ISSUE TITLE
Error in Chapter 2 Page 28

### ISSUE THREAD

**Issue by SSJUSA** [PacktPublishing/Mastering-Embedded-Linux-Programming-Third-Edition#49] opened 2021-10-30 07:07 UTC
I am getting following error in Chapter 2 page 28, while building tool chain for Beagle Bone Black:

bin/ct-ng build

EXTRA]    Retrieving 'isl-0.22'
[ERROR]    isl: download failed

Please help in fixing this error.
Thanks and best regards,

/crosstool-ng$ bin/ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20211030.041930
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = arm-cortex_a8-linux-gnueabihf
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.09s (at 00:02)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'isl-0.22'
[ERROR]    isl: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2125]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2085]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2196]
[ERROR]  >>        called from: do_isl_get[scripts/build/companion_libs/121-isl.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@647]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 1:40.44)
[01:41] / bin/ct-ng:261: recipe for target 'build' failed
make: *** [build] Error 1
owner@owner-Lenovo-IdeaPad-S340-15APITouch:~/crosstool-ng$

**Comment by fvasquez** [comment] 2022-01-01 01:34
The `isl: download failed` error is due to [this regression](https://github.com/crosstool-ng/crosstool-ng/issues/1609) in the crosstool-ng build. The error was later fixed by [this pull request](https://github.com/crosstool-ng/crosstool-ng/pull/1614).

To get past the `isl: download failed` error you have two options:

- Use one of the various workarounds described in the issue for the regression.
- Clone the latest source from the master branch of crostool-ng which includes the aforementioned fix.

**Closed as completed by fvasquez** 2022-01-01 01:34 UTC
